[package]
name = "cudup"
version = "0.3.0"
authors = ["Cristian Zoz <cristian@zoz.dev>"]
license = "MIT"
repository = "https://github.com/ZoCrit/cudup"
description = "CUDA version manager"
keywords = ["cuda", "version-manager", "gpu", "nvidia", "ml"]
categories = ["development-tools", "command-line-utilities"]
edition = "2024"

[dependencies]
anyhow = "1.0.100"
log = "0.4"
env_logger = "0.11"
clap = { version = "4.5.53", features = ["derive"] }
dirs = "6.0"
futures = "0.3.31"
regex = "1.11"
reqwest = { version = "0.12.28", default-features = false, features = ["json", "stream", "rustls-tls"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.148"
sha2 = "0.10"
tokio = { version = "1.48.0", features = ["rt-multi-thread", "macros", "fs", "io-util", "process"] }
indicatif = "0.17"

[profile.release]
codegen-units = 1
lto = true 
